### ISSUE TITLE
Incorrect stopping

### ISSUE THREAD

**Issue by danilkuzin** [raipe/gst-bda#1]
When stopping the pipeline that contains bdasrc element Gstreamer freezes on pipeline.SetState(State.Null) (this is for Gstreamer-sharp, but the same is for console Gstreamer too). And it does not stop at all. (I was waiting for 10 minutes)

**Comment by raipe** [comment]
This should be fixed in b8e2d81d8da2f62de5de669923f77963fba5af13

**Comment by danilkuzin** [comment]
Thank you
