### ISSUE TITLE
Freezing with incorrect frequency

### ISSUE THREAD

**Issue by danilkuzin** [raipe/gst-bda#2]
Specification of frequency that does not contain signal in DVB-T parameters leads to freeze at "Freeing pipeline". When the command is interrupted by me, the DVB-T receiver becomes unavailable and can't open the stream at correct frequency.

pipeline example:
gst-launch-1.0 bdasrc device=0 frequency=356000 ! decodebin name=dbin ! queue ! autovideosink dbin. ! queue ! audioconvert ! autoaudiosink

output:
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by raipe** [comment]
I wasn't able to reproduce the freeze with my DVB-C reveiver, but I hope 9002519b74375bad7c43a51ded0265512e5b697e fixes it.

**Comment by danilkuzin** [comment]
Thank you. It seems very strange to me now. 
When I launch the pipeline in console gstreamer using the gst-launch, it works good, even with incorrect frequency, i.e the pipeline is freed in a few seconds and I can restart it on correct frequency.  

But when I set the wrong frequency in .NET application with Gstreamer-sharp, the following happens:
1) Pipeline.SetState(State.Paused) returns StateChangeResult.Failure (that's ok)
2) I use Pipeline.SetState(State.Null), Pipeline.Unref(). pipeline = null - everything works there.
3) I exit the application, but the DVB-T receiver seems to be busy. Application remains in TaskList and I can't open the DVB-T stream in other applications.

I really don't have any ideas if it is due to Bdasrc plugin, Gstreamer-sharp, or device drivers. And in other test scenarios it exits without blocking the device.

**Comment by raipe** [comment]
I think releasing the filter graph (and the DVB device) was broken. I'm not sure if this was causing your problem, but I tried to fix it in 3a7a5dada826f7abe70e446935ce57d553f4fb48.

**Comment by danilkuzin** [comment]
Thank you! Now it handles the wrong frequency correctly.
